### ISSUE TITLE
无法启动插件

### ISSUE THREAD

**Issue by liuhy1989121** [Qihoo360/DroidPlugin#33]
成功安装插件后，打开插件为何一直报插件main activity没注册的错误？请问插件还要做什么特殊处理？

**Comment by cmzy** [comment]
请打开插件系统的日志，然后把详细日志发上来吧。

**Comment by xuliang271699** [comment]
我也无法启动插件的activity

Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.droidplugin.test.main/com.droidplugin.plus.MainActivity}; have you declared this activity in your AndroidManifest.xml?
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1634)
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1430)
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at android.app.Activity.startActivityForResult(Activity.java:3470)
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at android.app.Activity.startActivityForResult(Activity.java:3426)
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:820)
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at com.droidplugin.test.main.MainActivity.goPlus(MainActivity.java:59)
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at android.view.View$1.onClick(View.java:3965) 
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at android.view.View.performClick(View.java:4585) 
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:18971) 
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:808) 
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:103) 
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193) 
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5423) 
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:855) 
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671) 
09-22 17:05:05.090 21084-21084/com.droidplugin.test.main E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by cmzy** [comment]
不只是这个，还要插件系统的。插件系统会自动生成文件日志。

**Comment by xuliang271699** [comment]
在哪里看呢？

**Comment by cmzy** [comment]
看插件系统中Log.java的代码。

**Comment by cmzy** [comment]
请问是否解决了？你是否安装了什么安全软件？把他们卸载了呢？

**Comment by cmzy** [comment]
重复：

https://github.com/Qihoo360/DroidPlugin/issues/51

**Comment by huangjinhao** [comment]
怎么解决的
